x1 = int(input("أدخل العدد الأول:"))
x2 = int(input("أدخل العدد الثاني:"))
print(x1, " + ", x2, " = ", x1 + x2)
print(x1, " - ", x2, " = ", x1 - x2)
print(x1, " × ", x2, " = ", x1 * x2)
print(x1, " ÷ ", x2, " = ", x1 / x2)
